---
title: "StormEMG"
author: "Allyson Clarke"
format: html
editor: visual
---

```{r}
#| label: load_libraries


library(tidyverse)
library(conflicted)
conflict_prefer("filter", "dplyr")

source("filter_emg.R")
source("read_emg_txt.R")

```

```{r}
#| label: set_metadata

# muscle names in order of sensors
emg_labels <- c("LRF", "RRF", "LVL", "RVM", "LVM", "RVL", "LBF", "RBF", "LST", "RST", "LGAS", "RGAS", "LGMED", "RGMED")

# sampling frequency
sf <- 2148 


```


```{r}
#| label: get_mvcs

# order of MVC exercises: Plantarflexor (GAS), hamstring (ST, BF), Hip AD (GMED?), Hip AB (GMED?), Quad (VL, RF, VM)

# read in mvc data
mvc_raw <- read_emg_txt("../Data/EMG/MVC2.txt", emg_labels)

# filter mvc data
filt_mvc <- filter_emg(mvc_raw, sf) 

# add time column
filt_mvc$t <- seq(0, nrow(filt_mvc) - 1) / sf

# plotting to visualize MVC trials- you can see that BF and RVM sensors fell off/were removed
pltdf <- filt_mvc %>% slice(seq(1, n(), by = 10)) %>%
  pivot_longer(cols = -t, names_to = "muscle", values_to = "value")

ggplot(pltdf, aes(x = t, y = value)) + 
  geom_line() + 
  facet_wrap(~muscle, scales= "free_y") +
  labs(title = "MVC Data", x = "Time (s)", y = "EMG Signal") +
  theme_minimal()
  

# sensors that fell off: RVM, RVM (again), LBF + RBF
# for BF, change all values after 900s to 0 (MVC for these muscles should have been much earlier, after ~900s the sensors were removed for comfort)
# for RVM, change all values between 547-702 and 810-894 to 0 (around the time this sensor fell off)

# There might be a better way to do this but felt good enough for now. Something funky is also going on with LVM, haven't figured that out yet
filt_mvc <- filt_mvc %>%
  mutate(RBF = ifelse(t > 900, 0, RBF), 
         LBF = ifelse(t > 900, 0, LBF), 
         RVM = ifelse((t > 547 & t < 702) | (t > 810 & t < 894), 0, RVM))



# get the max of each channel
mvc_max <- filt_mvc %>% 
  summarise(across(-t, max)) %>% 
  as.numeric()

# alternatively, try 95% - this didn't work as well when I was messing around with data
mvc95 <- filt_mvc %>% 
  summarise(across(everything(), ~ quantile(., 0.95))) %>% 
  as.numeric()


```


```{r}
#| label: process_trial

# read trial
trial_raw <- read_emg_txt("../Data/EMG/run1.txt", emg_labels)


# filter trial
trial_filt <- filter_emg(trial_raw, sf)

# normalize to MVC (can switch between mvc_max and mvc95 to see effect of normalization method)
trial_norm <- sweep(trial_filt, 2, mvc_max, FUN = "/")

# add time column
trial_norm$t <- seq(0, nrow(trial_norm) - 1) / sf


# plot muscle activity over trial
plot_df <- trial_norm %>% pivot_longer(cols = -t, names_to = "muscle", values_to = "value")

ggplot(plot_df, aes(x= t, y= value)) + geom_line() + facet_wrap(~muscle) +
  labs(title = "Normalized EMG Trial Data", x = "Time (s)", y = "Normalized EMG Signal") +
  theme_minimal()
```

